#+TITLE: Использование подпрограмм в системе MATLAB

* Индивидуальное задание

Цель работы: Знакомство с организацией функций в MATLAB,
особенностями их работы.

В ходе выполнения индивидуального задания будет использовать вариант под номером 4.

1. Написать функцию f1, которая будет рассчитывать значение
   кусочно заданной функции (см. лабораторную работу №2).
   Входным параметром функции является скаляр –
   аргумент кусочно заданной функции.
   Выходным параметром функции является скаляр -
   значение кусочно заданной функции в точке-аргументе.
   Если аргумент функции не принадлежит области определения функции,
   должно быть выведено соответствующее сообщение и работа функции
   должна быть остановлена. Текст функции сопроводить комментариями. 
2. Написать скрипт definition_anfun, содержащий определение анонимной функции f2 (см. табл. 2, функция для задания №2, лабораторная работа №1);
3. Написать программу-сценарий (скрипт), которая:
   - сформирует вектор x с использованием оператора двоеточия со значениями от xMin до xMax с шагом dx=0.1, где xMin и xMax – левая и правая границы интервала, на котором определена функция, соответственно; 
   - для каждого элемента созданного вектора x вычислит значения с использованием функции f1 и запишет результат в вектор y1;
   - вызовет скрипт definition_anfun с определением анонимной функции f2;
   - для каждого элемента вектора x вычислит значения с использованием анонимной функции f2 и запишет результат в вектор y2;
   - построить графики двух заданных функций в рамках одного окна, используя векторы x, y1 и y2, добавит к графику заголовок и легенду (при необходимости, использовать масштабирование для более наглядного отображения графиков функций)
4. Весь написанный программный код необходимо сопроводить комментариями, созданные скрипты и функции – документированием (заголовочным комментарием)
5. Используя результаты лабораторных работ №2 и №3, сделать выводы по использованию программ-сценариев (скриптов) и функций для решения одной и той же задачи.


